defmodule IPStruct do
  defstruct original_ip_address: nil,
            original_subnet_mask: nil,
            original_ip_address_list: nil,
            original_subnet_mask_list: nil,
            first_ip_octet_decimal: nil,
            second_ip_octet_decimal: nil,
            third_ip_octet_decimal: nil,
            fourth_ip_octet_decimal: nil,
            first_mask_octet_decimal: nil,
            second_mask_octet_decimal: nil,
            third_mask_octet_decimal: nil,
            fourth_mask_octet_decimal: nil,
            first_ip_octet_binary: nil,
            second_ip_octet_binary: nil,
            third_ip_octet_binary: nil,
            fourth_ip_octet_binary: nil,
            first_mask_octet_binary: nil,
            second_mask_octet_binary: nil,
            third_mask_octet_binary: nil,
            fourth_mask_octet_binary: nil,
            combined_bin_ip: nil,
            combined_bin_mask: nil,
            network_portion_of_ip: nil,
            zeroes_for_subnet_address: nil,
            ones_for_broadcast_address: nil,
            binary_subnet_address: nil,
            binary_broadcast_address: nil,
            number_of_ones_in_mask: nil,
            network_portion_of_ip: nil,
            zeroes_for_subnet_address: nil,
            ones_for_broadcast_address: nil
end
